name: Run Trivy Scan

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Push on DockerHub"]
    types:
      - completed

permissions:
  contents: write

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create reports directory
        run: mkdir -p security-reports

      - name: Scan Ubuntu Noble Image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 'docker.io/karfee111/do-agent:noble-latest'
          format: 'json'
          output: '.github/security-reports/noble-vulnerabilities.json'
          severity: 'HIGH,CRITICAL'

      - name: Scan Debian Trixie Image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 'docker.io/karfee111/do-agent:trixie-latest'
          format: 'json'
          output: '.github/security-reports/trixie-vulnerabilities.json'
          severity: 'HIGH,CRITICAL'

      - name: Commit and Push JSON Reports
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add security-reports/
          git commit -m "Update security scan reports" || echo "No changes to commit"
          git push origin main
